// Shevet wire protocol, v1.
//
// This package defines the gRPC surface between the Server (`shevet serve`)
// and Clients (`shevet connect`). It is served on a unix socket and reached
// through an SSH tunnel; SSH is the sole authentication and authorization
// boundary (see docs/adr/0003-grpc-over-ssh-tunnel.md).
//
// Vocabulary (Herd, Pane, Agent, ...) follows CONTEXT.md.
//
// Regenerate with `make proto`.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: shevet/v1/shevet.proto

package shevetv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HerdService_ListPanes_FullMethodName = "/shevet.v1.HerdService/ListPanes"
	HerdService_WatchPane_FullMethodName = "/shevet.v1.HerdService/WatchPane"
)

// HerdServiceClient is the client API for HerdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HerdService is the Server's control-plane API: enumerating and (in later
// slices) managing the Panes that make up the Herd.
type HerdServiceClient interface {
	// ListPanes returns every Pane currently in the Herd.
	ListPanes(ctx context.Context, in *ListPanesRequest, opts ...grpc.CallOption) (*ListPanesResponse, error)
	// WatchPane is the Matrix Render stream for one Pane: cell damage,
	// cursor movement, and resizes, until the Pane exits or the Client
	// hangs up. The first updates always establish the full current state
	// (a resize followed by damage covering every non-default cell); after
	// that, damage carries only cells that changed — never full frames.
	WatchPane(ctx context.Context, in *WatchPaneRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PaneUpdate], error)
}

type herdServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHerdServiceClient(cc grpc.ClientConnInterface) HerdServiceClient {
	return &herdServiceClient{cc}
}

func (c *herdServiceClient) ListPanes(ctx context.Context, in *ListPanesRequest, opts ...grpc.CallOption) (*ListPanesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPanesResponse)
	err := c.cc.Invoke(ctx, HerdService_ListPanes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *herdServiceClient) WatchPane(ctx context.Context, in *WatchPaneRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PaneUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HerdService_ServiceDesc.Streams[0], HerdService_WatchPane_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchPaneRequest, PaneUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HerdService_WatchPaneClient = grpc.ServerStreamingClient[PaneUpdate]

// HerdServiceServer is the server API for HerdService service.
// All implementations must embed UnimplementedHerdServiceServer
// for forward compatibility.
//
// HerdService is the Server's control-plane API: enumerating and (in later
// slices) managing the Panes that make up the Herd.
type HerdServiceServer interface {
	// ListPanes returns every Pane currently in the Herd.
	ListPanes(context.Context, *ListPanesRequest) (*ListPanesResponse, error)
	// WatchPane is the Matrix Render stream for one Pane: cell damage,
	// cursor movement, and resizes, until the Pane exits or the Client
	// hangs up. The first updates always establish the full current state
	// (a resize followed by damage covering every non-default cell); after
	// that, damage carries only cells that changed — never full frames.
	WatchPane(*WatchPaneRequest, grpc.ServerStreamingServer[PaneUpdate]) error
	mustEmbedUnimplementedHerdServiceServer()
}

// UnimplementedHerdServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHerdServiceServer struct{}

func (UnimplementedHerdServiceServer) ListPanes(context.Context, *ListPanesRequest) (*ListPanesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPanes not implemented")
}
func (UnimplementedHerdServiceServer) WatchPane(*WatchPaneRequest, grpc.ServerStreamingServer[PaneUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchPane not implemented")
}
func (UnimplementedHerdServiceServer) mustEmbedUnimplementedHerdServiceServer() {}
func (UnimplementedHerdServiceServer) testEmbeddedByValue()                     {}

// UnsafeHerdServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HerdServiceServer will
// result in compilation errors.
type UnsafeHerdServiceServer interface {
	mustEmbedUnimplementedHerdServiceServer()
}

func RegisterHerdServiceServer(s grpc.ServiceRegistrar, srv HerdServiceServer) {
	// If the following call panics, it indicates UnimplementedHerdServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HerdService_ServiceDesc, srv)
}

func _HerdService_ListPanes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPanesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HerdServiceServer).ListPanes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HerdService_ListPanes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HerdServiceServer).ListPanes(ctx, req.(*ListPanesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HerdService_WatchPane_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchPaneRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HerdServiceServer).WatchPane(m, &grpc.GenericServerStream[WatchPaneRequest, PaneUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HerdService_WatchPaneServer = grpc.ServerStreamingServer[PaneUpdate]

// HerdService_ServiceDesc is the grpc.ServiceDesc for HerdService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HerdService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shevet.v1.HerdService",
	HandlerType: (*HerdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPanes",
			Handler:    _HerdService_ListPanes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchPane",
			Handler:       _HerdService_WatchPane_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "shevet/v1/shevet.proto",
}
