// Shevet wire protocol, v1.
//
// This package defines the gRPC surface between the Server (`shevet serve`)
// and Clients (`shevet connect`). It is served on a unix socket and reached
// through an SSH tunnel; SSH is the sole authentication and authorization
// boundary (see docs/adr/0003-grpc-over-ssh-tunnel.md).
//
// Vocabulary (Herd, Pane, Agent, ...) follows CONTEXT.md.
//
// Regenerate with `make proto`.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: shevet/v1/shevet.proto

package shevetv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPanesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPanesRequest) Reset() {
	*x = ListPanesRequest{}
	mi := &file_shevet_v1_shevet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPanesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPanesRequest) ProtoMessage() {}

func (x *ListPanesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shevet_v1_shevet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPanesRequest.ProtoReflect.Descriptor instead.
func (*ListPanesRequest) Descriptor() ([]byte, []int) {
	return file_shevet_v1_shevet_proto_rawDescGZIP(), []int{0}
}

type ListPanesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Panes         []*Pane                `protobuf:"bytes,1,rep,name=panes,proto3" json:"panes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPanesResponse) Reset() {
	*x = ListPanesResponse{}
	mi := &file_shevet_v1_shevet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPanesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPanesResponse) ProtoMessage() {}

func (x *ListPanesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shevet_v1_shevet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPanesResponse.ProtoReflect.Descriptor instead.
func (*ListPanesResponse) Descriptor() ([]byte, []int) {
	return file_shevet_v1_shevet_proto_rawDescGZIP(), []int{1}
}

func (x *ListPanesResponse) GetPanes() []*Pane {
	if x != nil {
		return x.Panes
	}
	return nil
}

// Pane is one Agent's terminal surface, owned by tmux and interpreted by the
// Server (see CONTEXT.md). Fields are additive; later slices extend this
// message with Status, provenance (Spawned/Adopted), and geometry.
type Pane struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the Server-scoped stable identifier of the Pane.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// title is a human-readable label for dashboards.
	Title         string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pane) Reset() {
	*x = Pane{}
	mi := &file_shevet_v1_shevet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pane) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pane) ProtoMessage() {}

func (x *Pane) ProtoReflect() protoreflect.Message {
	mi := &file_shevet_v1_shevet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pane.ProtoReflect.Descriptor instead.
func (*Pane) Descriptor() ([]byte, []int) {
	return file_shevet_v1_shevet_proto_rawDescGZIP(), []int{2}
}

func (x *Pane) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pane) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_shevet_v1_shevet_proto protoreflect.FileDescriptor

const file_shevet_v1_shevet_proto_rawDesc = "" +
	"\n" +
	"\x16shevet/v1/shevet.proto\x12\tshevet.v1\"\x12\n" +
	"\x10ListPanesRequest\":\n" +
	"\x11ListPanesResponse\x12%\n" +
	"\x05panes\x18\x01 \x03(\v2\x0f.shevet.v1.PaneR\x05panes\",\n" +
	"\x04Pane\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title2U\n" +
	"\vHerdService\x12F\n" +
	"\tListPanes\x12\x1b.shevet.v1.ListPanesRequest\x1a\x1c.shevet.v1.ListPanesResponseB4Z2github.com/irodion/shevet/proto/shevet/v1;shevetv1b\x06proto3"

var (
	file_shevet_v1_shevet_proto_rawDescOnce sync.Once
	file_shevet_v1_shevet_proto_rawDescData []byte
)

func file_shevet_v1_shevet_proto_rawDescGZIP() []byte {
	file_shevet_v1_shevet_proto_rawDescOnce.Do(func() {
		file_shevet_v1_shevet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shevet_v1_shevet_proto_rawDesc), len(file_shevet_v1_shevet_proto_rawDesc)))
	})
	return file_shevet_v1_shevet_proto_rawDescData
}

var file_shevet_v1_shevet_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shevet_v1_shevet_proto_goTypes = []any{
	(*ListPanesRequest)(nil),  // 0: shevet.v1.ListPanesRequest
	(*ListPanesResponse)(nil), // 1: shevet.v1.ListPanesResponse
	(*Pane)(nil),              // 2: shevet.v1.Pane
}
var file_shevet_v1_shevet_proto_depIdxs = []int32{
	2, // 0: shevet.v1.ListPanesResponse.panes:type_name -> shevet.v1.Pane
	0, // 1: shevet.v1.HerdService.ListPanes:input_type -> shevet.v1.ListPanesRequest
	1, // 2: shevet.v1.HerdService.ListPanes:output_type -> shevet.v1.ListPanesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shevet_v1_shevet_proto_init() }
func file_shevet_v1_shevet_proto_init() {
	if File_shevet_v1_shevet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shevet_v1_shevet_proto_rawDesc), len(file_shevet_v1_shevet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shevet_v1_shevet_proto_goTypes,
		DependencyIndexes: file_shevet_v1_shevet_proto_depIdxs,
		MessageInfos:      file_shevet_v1_shevet_proto_msgTypes,
	}.Build()
	File_shevet_v1_shevet_proto = out.File
	file_shevet_v1_shevet_proto_goTypes = nil
	file_shevet_v1_shevet_proto_depIdxs = nil
}
